title: <p align="center"> Hugo Arellano </p>

logo: "/assets/img/profile_hugo_arellano.png?raw=true" 

description: <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://github.com/harellano1">GitHub</a>
  </p>
  
  <p align="justify">
  I consider myself as an inveterate learner and passionate of the economy,
  specially in the branches that involve behavior, microeconomics,
  programming and technology.
  </p>

google_analytics:
theme: jekyll-theme-minimal
