title: <p align="center"> Hugo Arellano </p>
logo: /assets/img/profile_hugo_arellano.png 
alt= "Economista Ciencia de Datos Colima"


description: Welcome to my website
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
